---
- name: Configure demo boxes
  hosts: all
  sudo_user: root
  sudo: true
  vars_files:
  - netvars/net.yml

  roles:
  - common

- name: Deploy Tower
  hosts: towerf
  sudo_user: root
  sudo: true
  vars_files:
  - netvars/net.yml
  
  roles:
  - tower
